<a href="https://colab.research.google.com/github/hst8486-collab/thuc-hanh--deep-learning/blob/main/B%C3%A0i_th%E1%BB%B1c_h%C3%A0nh_tu%E1%BA%A7n_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# bài thực hành numpy

In [1]:
# tạo mảng 1 chiều numpy

import numpy as np

my_list = [1,9,15,39]
print('list: ', my_list)
my_numpy_arr = np.array(my_list) # chuyển list sang numpy array
print('numpy array: ', my_numpy_arr)

list:  [1, 9, 15, 39]
numpy array:  [ 1  9 15 39]


In [ ]:
# tạo mảng 2 chiều numpy

import numpy as np

a = np.array([(1,2,3),(4,5,6)])
print(a)
print(a.shape) # kích thước mảng
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
# tạo mảng 3 chiều

import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1

import numpy as np

a = np.zeros((2,3))
print('mảng toàn số 0: \n', a)
b = np.ones((3,3))
print('mảng toàn số 1: \n',b)

mảng toàn số 0: 
 [[0. 0. 0.]
 [0. 0. 0.]]
mảng toàn số 1: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# thay đổi kích thước mảng

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("mảng a: \n", a)
print(a.shape)

# đổi kích thước mảng
b = a.reshape(3,2)
print("mảng b: \n", b)
print(b.shape)

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("mảng c: \n", c)
print(c.shape)

d = c.reshape(3,4)
print("mảng d: \n", d)
print(d.shape)

e = d.reshape(3,2,2)
print("mảng e: \n", e)
print(e.shape)

mảng a: 
 [[1 2 3]
 [4 5 6]]
(2, 3)
mảng b: 
 [[1 2]
 [3 4]
 [5 6]]
(3, 2)
mảng c: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
mảng d: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
mảng e: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [ ]:
# chuyển mảng nhiều chiều về 1 chiều

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("mảng a: \n",a)
b = a.flatten()
print("mảng b: \n", b)

mảng a: 
 [[1 2 3]
 [4 5 6]]
mảng b: 
 [1 2 3 4 5 6]


In [ ]:
# thêm dòng dữ liệu

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# thêm dữ liệu theo chiều dọc
h_stack = np.hstack((a,b))
print("horizontal append: \n", h_stack)

# thêm dữ liệu theo chiều ngang
v_stack = np.vstack((a,b))
print("vertical append: \n", v_stack)

horizontal append: 
 [1 2 3 4 5 6]
vertical append: 
 [[1 2 3]
 [4 5 6]]


In [ ]:
# tạo mảng ngẫu nhiên

import numpy as np

a = np.random.randint(100, size=(5,))
print("\n",a)

b = np.random.randint(100, size=(2,3))
print("\n",b)

c = np.random.randint(100, size=(3,2,3))
print("\n",c)


 [68 72 81 37 52]

 [[70 73 91]
 [86 68 63]]

 [[[24 23 46]
  [81 25 72]]

 [[52 69 54]
  [89 72 55]]

 [[62 35 42]
  [48 27 35]]]


# bài thực hành pandas

In [ ]:
# tạo pandas từ list

import pandas as pd

a = pd.Series([1,2,3,4,5])
print(a)
print("giá trị đầu: ", a[0])
b = pd.Series ([1,2,3], index = ['a','b','c'])
print(b)
print ("giá trị đầu: ", b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1
1    2
2    3
3    4
4    5
dtype: int64
giá trị đầu:  1
a    1
b    2
c    3
dtype: int64
giá trị đầu:  1
day1    420
day2    380
day3    390
dtype: int64


In [4]:
#tạo data frame

import numpy as np
import pandas as pd

a = np.array([[1,2],[3,4]])

df_a = pd.DataFrame(a)
print("Data frame: \n", df_a)

np_a = np.array(df_a)
print("Numpy: \n", np_a)

Data frame: 
    0  1
0  1  2
1  3  4
Numpy: 
 [[1 2]
 [3 4]]


In [5]:
# tạo data frame mảng 2 chiều có tên cột

import pandas as pd

data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [10]:
# tạo mảng 20x4

import numpy as np
import pandas as pd

a = np.random.randn(20,4)
df = pd.DataFrame(a, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

        so1       so2       so3       so4
0  1.066477 -0.544184  0.334669 -0.101003
1  0.209435  0.129541  1.333897  1.644508
2 -0.912628  0.189125 -0.209987  0.135553
3 -1.123183  1.343390 -2.071444 -1.077635
4 -1.119790  1.911872 -0.159627  0.778787


In [14]:
# Slice DataFrame

import pandas as pd
import numpy as np

a = np.random.randn(20,4)
df = pd.DataFrame(a, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

# chọn 1 cột
print("chọn cột số 1 \n", df['so1'])

# chọn nhiều dòng
print("chọn nhiều dòng \n", df[0:3])

# chọn nhiều cột
print("chọn nhiều cột \n", df[['so1', 'so3']])

# chọn nhiều dòng , cột
print("chọn nhiều dòng và cột \n",  df.iloc[:3, :2])

        so1       so2       so3       so4
0  0.473540  0.244819 -0.425968  0.435318
1 -1.030880 -0.080544  2.354207  1.079714
2 -1.544981 -0.818213 -1.061996  1.081469
3  1.586268 -0.874938 -0.354113 -0.921464
4 -0.312075 -0.747683  1.132068  0.668320
chọn cột số 1 
 0     0.473540
1    -1.030880
2    -1.544981
3     1.586268
4    -0.312075
5     0.400320
6     0.384648
7     0.590643
8    -1.269605
9     0.707366
10    0.710373
11    0.005047
12    0.241951
13    0.411399
14    0.228745
15   -0.787535
16    0.441296
17   -0.013391
18   -1.470750
19    1.257817
Name: so1, dtype: float64
chọn nhiều dòng 
         so1       so2       so3       so4
0  0.473540  0.244819 -0.425968  0.435318
1 -1.030880 -0.080544  2.354207  1.079714
2 -1.544981 -0.818213 -1.061996  1.081469
chọn nhiều cột 
          so1       so3
0   0.473540 -0.425968
1  -1.030880  2.354207
2  -1.544981 -1.061996
3   1.586268 -0.354113
4  -0.312075  1.132068
5   0.400320  1.726544
6   0.384648 -0.798962
7   0.590643  1.085