<a href="https://colab.research.google.com/github/hst8486-collab/thuc-hanh--deep-learning/blob/main/B%C3%A0i_th%E1%BB%B1c_h%C3%A0nh_tu%E1%BA%A7n_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# bài thực hành numpy

In [1]:
# tạo mảng 1 chiều numpy

import numpy as np

my_list = [1,9,15,39]
print('list: ', my_list)
my_numpy_arr = np.array(my_list) # chuyển list sang numpy array
print('numpy array: ', my_numpy_arr)

list:  [1, 9, 15, 39]
numpy array:  [ 1  9 15 39]


In [ ]:
# tạo mảng 2 chiều numpy

import numpy as np

a = np.array([(1,2,3),(4,5,6)])
print(a)
print(a.shape) # kích thước mảng
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
# tạo mảng 3 chiều

import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1

import numpy as np

a = np.zeros((2,3))
print('mảng toàn số 0: \n', a)
b = np.ones((3,3))
print('mảng toàn số 1: \n',b)

mảng toàn số 0: 
 [[0. 0. 0.]
 [0. 0. 0.]]
mảng toàn số 1: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# thay đổi kích thước mảng

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("mảng a: \n", a)
print(a.shape)

# đổi kích thước mảng
b = a.reshape(3,2)
print("mảng b: \n", b)
print(b.shape)

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("mảng c: \n", c)
print(c.shape)

d = c.reshape(3,4)
print("mảng d: \n", d)
print(d.shape)

e = d.reshape(3,2,2)
print("mảng e: \n", e)
print(e.shape)

mảng a: 
 [[1 2 3]
 [4 5 6]]
(2, 3)
mảng b: 
 [[1 2]
 [3 4]
 [5 6]]
(3, 2)
mảng c: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
mảng d: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
mảng e: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [ ]:
# chuyển mảng nhiều chiều về 1 chiều

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("mảng a: \n",a)
b = a.flatten()
print("mảng b: \n", b)

mảng a: 
 [[1 2 3]
 [4 5 6]]
mảng b: 
 [1 2 3 4 5 6]


In [ ]:
# thêm dòng dữ liệu

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# thêm dữ liệu theo chiều dọc
h_stack = np.hstack((a,b))
print("horizontal append: \n", h_stack)

# thêm dữ liệu theo chiều ngang
v_stack = np.vstack((a,b))
print("vertical append: \n", v_stack)

horizontal append: 
 [1 2 3 4 5 6]
vertical append: 
 [[1 2 3]
 [4 5 6]]


In [ ]:
# tạo mảng ngẫu nhiên

import numpy as np

a = np.random.randint(100, size=(5,))
print("\n",a)

b = np.random.randint(100, size=(2,3))
print("\n",b)

c = np.random.randint(100, size=(3,2,3))
print("\n",c)


 [68 72 81 37 52]

 [[70 73 91]
 [86 68 63]]

 [[[24 23 46]
  [81 25 72]]

 [[52 69 54]
  [89 72 55]]

 [[62 35 42]
  [48 27 35]]]


# bài thực hành pandas

In [ ]:
# tạo pandas từ list

import pandas as pd

a = pd.Series([1,2,3,4,5])
print(a)
print("giá trị đầu: ", a[0])
b = pd.Series ([1,2,3], index = ['a','b','c'])
print(b)
print ("giá trị đầu: ", b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1
1    2
2    3
3    4
4    5
dtype: int64
giá trị đầu:  1
a    1
b    2
c    3
dtype: int64
giá trị đầu:  1
day1    420
day2    380
day3    390
dtype: int64


In [4]:
#tạo data frame

import numpy as np
import pandas as pd

a = np.array([[1,2],[3,4]])

df_a = pd.DataFrame(a)
print("Data frame: \n", df_a)

np_a = np.array(df_a)
print("Numpy: \n", np_a)

Data frame: 
    0  1
0  1  2
1  3  4
Numpy: 
 [[1 2]
 [3 4]]


In [5]:
# tạo data frame mảng 2 chiều có tên cột

import pandas as pd

data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [10]:
# tạo mảng 20x4

import numpy as np
import pandas as pd

a = np.random.randn(20,4)
df = pd.DataFrame(a, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

        so1       so2       so3       so4
0  1.066477 -0.544184  0.334669 -0.101003
1  0.209435  0.129541  1.333897  1.644508
2 -0.912628  0.189125 -0.209987  0.135553
3 -1.123183  1.343390 -2.071444 -1.077635
4 -1.119790  1.911872 -0.159627  0.778787


In [14]:
# Slice DataFrame

import pandas as pd
import numpy as np

a = np.random.randn(20,4)
df = pd.DataFrame(a, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

# chọn 1 cột
print("chọn cột số 1 \n", df['so1'])

# chọn nhiều dòng
print("chọn nhiều dòng \n", df[0:3])

# chọn nhiều cột
print("chọn nhiều cột \n", df[['so1', 'so3']])

# chọn nhiều dòng , cột
print("chọn nhiều dòng và cột \n",  df.iloc[:3, :2])

        so1       so2       so3       so4
0  0.473540  0.244819 -0.425968  0.435318
1 -1.030880 -0.080544  2.354207  1.079714
2 -1.544981 -0.818213 -1.061996  1.081469
3  1.586268 -0.874938 -0.354113 -0.921464
4 -0.312075 -0.747683  1.132068  0.668320
chọn cột số 1 
 0     0.473540
1    -1.030880
2    -1.544981
3     1.586268
4    -0.312075
5     0.400320
6     0.384648
7     0.590643
8    -1.269605
9     0.707366
10    0.710373
11    0.005047
12    0.241951
13    0.411399
14    0.228745
15   -0.787535
16    0.441296
17   -0.013391
18   -1.470750
19    1.257817
Name: so1, dtype: float64
chọn nhiều dòng 
         so1       so2       so3       so4
0  0.473540  0.244819 -0.425968  0.435318
1 -1.030880 -0.080544  2.354207  1.079714
2 -1.544981 -0.818213 -1.061996  1.081469
chọn nhiều cột 
          so1       so3
0   0.473540 -0.425968
1  -1.030880  2.354207
2  -1.544981 -1.061996
3   1.586268 -0.354113
4  -0.312075  1.132068
5   0.400320  1.726544
6   0.384648 -0.798962
7   0.590643  1.085

In [17]:
# nối data frame

import pandas as pd

df1 = pd.DataFrame({'Name': ['Jhon', 'Smith', 'Paul'], 'Age': [25,30,50]}, index=[0,1,2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [26, 11]}, index=[3,4])
df_contact = pd.concat([df1, df2])
print('nối data frame \n',df_contact)

# xóa những giá trị trùng nhau ở cột Name
print("xóa giá trị trùng ở cột Name \n", df_contact.drop_duplicates('Name'))

# sắp xếp theo cột
print("sắp xếp theo cột \n", df_contact.sort_values('Age'))

# đổi tên cột
print("đổi tên cột \n", df_contact.rename(columns={'Name':'Tên', 'Age':'Tuổi'}))

nối data frame 
     Name  Age
0   Jhon   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
xóa giá trị trùng ở cột Name 
     Name  Age
0   Jhon   25
1  Smith   30
2   Paul   50
3   Adam   26
sắp xếp theo cột 
     Name  Age
4  Smith   11
0   Jhon   25
3   Adam   26
1  Smith   30
2   Paul   50
đổi tên cột 
      Tên  Tuổi
0   Jhon    25
1  Smith    30
2   Paul    50
3   Adam    26
4  Smith    11


# THỰC HÀNH 2 : TENSORFLOW

In [18]:
# tạo tensor 0 chiều

import tensorflow as tf

tensor = tf.constant(4)

print(tensor)


tf.Tensor(4, shape=(), dtype=int32)


In [19]:
# tạo một tensor scalar với kiểu dữ liệu là int16, float32 và string

import tensorflow as tf

# tensor scalar với kiểu dữ liệu int16
tensor_int16 = tf.constant(4, dtype=tf.int16)
print(tensor_int16)

# tensor scalar với kiểu dữ liệu float32
tensor_float32 = tf.constant(4.0, dtype=tf.float32)
print(tensor_float32)

# tensor scalar với kiểu dữ liệu string
tensor_string = tf.constant("Hello, TensorFlow!", dtype=tf.string)
print(tensor_string)


tf.Tensor(4, shape=(), dtype=int16)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)


In [20]:
# tạo tensor 1 chiều

import tensorflow as tf

tensor_1d = tf.constant([1,2,3])
print(tensor_1d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [21]:
# tạo tensor 2 chiều

import tensorflow as tf

tensor_2d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [22]:
# tạo tensor nhiều chiều

import tensorflow as tf

tensor_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_3d)


tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [23]:
# tạo tensor với giá trị 0 ban đầu

import tensorflow as tf

tensor_zeros = tf.zeros(10)
print(tensor_zeros)


tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [24]:
import tensorflow as tf

tensor_zeros = tf.zeros([3,3])
print(tensor_zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [25]:
# tạo tensor với giá trị 1 ban đầu

import tensorflow as tf

tensor_zeros = tf.ones(10)
print(tensor_zeros)


tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [26]:
import tensorflow as tf

tensor_zeros = tf.ones([3,3])
print(tensor_zeros)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [27]:
# tạo tensor với giá trị bất kì

import tensorflow as tf

tensor = tf.fill(3,10)
print(tensor)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [29]:
import tensorflow as tf

tensor = tf.fill([3,3],10)
print(tensor)

tf.Tensor(
[[10 10 10]
 [10 10 10]
 [10 10 10]], shape=(3, 3), dtype=int32)


In [30]:
# Tạo tensor 1-chiều với hàm linspace

tensor = tf.linspace(5,20,5)
print(tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float64)


In [31]:
# Tạo tensor 1-chiều với hàm range

tensor = tf.range(3,7, delta = 0.5)
print(tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [32]:
# tạo tensor ngẫu nhiên với hàm random.normal

tensor = tf.random.normal([5])
print(tensor)

tf.Tensor([-1.1129564  -1.8126222  -1.2970022   1.021807    0.17360495], shape=(5,), dtype=float32)


In [33]:
tensor = tf.random.normal([3,3])
print(tensor)

tf.Tensor(
[[ 0.94100964 -0.26841423  1.6730912 ]
 [ 0.5538407  -0.15473187  0.22802418]
 [-0.20975451 -1.7397938   0.4774194 ]], shape=(3, 3), dtype=float32)


In [34]:
# tạo tensor ngẫu nhiên với hàm random.truncated_normal

tensor = tf.random.truncated_normal([5])
print(tensor)

tf.Tensor([ 0.4518433 -1.2024999 -1.351478   1.4701438  0.2948763], shape=(5,), dtype=float32)


In [35]:
tensor = tf.random.truncated_normal([5,3])
print(tensor)

tf.Tensor(
[[ 1.5533824   0.580606   -0.04051223]
 [ 0.11612624 -0.6377738  -0.6368944 ]
 [-0.7391243   0.55151373 -0.2409815 ]
 [ 1.0282183  -0.46861324 -1.0141022 ]
 [-1.114452    0.4267263   0.2078808 ]], shape=(5, 3), dtype=float32)


In [36]:
# tạo tensor ngẫu nhiên với hàm random.uniform

tensor = tf.random.uniform([5], minval = 10, maxval = 20)
print(tensor)

tf.Tensor([18.540257 15.237982 19.436909 12.017511 10.393089], shape=(5,), dtype=float32)


In [37]:
tensor = tf.random.uniform([5,3], minval = 10, maxval = 20)
print(tensor)

tf.Tensor(
[[15.243179  18.973074  15.090102 ]
 [18.449383  17.108126  10.278999 ]
 [13.344031  13.425949  15.9549055]
 [13.820205  10.723846  10.226654 ]
 [16.654533  10.282085  18.062191 ]], shape=(5, 3), dtype=float32)


In [38]:
# tạo tensor ngẫu nhiên với hàm random.uniform và dùng shuffle để xáo trộn giá trị trong tensor

tensor = tf.random.uniform([5], minval=10, maxval = 20)
print(tensor)
print(tf.random.shuffle(tensor))

tf.Tensor([15.221249 12.230621 16.266527 12.446047 14.441772], shape=(5,), dtype=float32)
tf.Tensor([16.266527 15.221249 12.230621 14.441772 12.446047], shape=(5,), dtype=float32)


In [39]:
# chuyển đổi kiểu dữ liệu tensorflow

t_float = tf.constant(3.5, tf.float32)
print(t_float, '---', t_float.dtype)
t_in = tf.cast(t_float, tf.int32)
print(t_in, '---', t_in.dtype)


tf.Tensor(3.5, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


In [41]:
# các phép toán trong tensorflow
# tính căn bậc 2 của tensor

x = tf.constant(4, dtype = tf.float32)
print(tf.sqrt(x))

tf.Tensor(2.0, shape=(), dtype=float32)


In [42]:
# cộng 2 tensor

a = tf.constant([1,2,3], tf.int32)
b = tf.constant([4,5,6], tf.int32)
c = tf.add(a,b)
d = a + b
print(c)
print(d)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [44]:
# nhân 2 tensor

a = tf.constant([1,2,3], tf.int32)
b = tf.constant([4,5,6], tf.int32)
c = tf.multiply(a,b)
d = a * b
print(c)
print(d)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [56]:
import tensorflow as tf

a = tf.constant([6,6,6])
b = tf.constant([4,4,4])
c = tf.constant([3,3,3])

d = tf.add(a,b)
print(d)

e = tf.add_n([a,b,c])
print(e)

f = tf.subtract(a,b)
print(f)

g = tf.multiply(a,b)
print(g)

h = tf.divide(a,b)
print(h)

i = tf.scalar_mul(3,a)
print(i)

j = tf.math.reciprocal(tf.cast(a, tf.float32))
print(j)

k = tf.math.mod(a,b)
print(k)

l = tf.negative(a)
print(l)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([13 13 13], shape=(3,), dtype=int32)
tf.Tensor([2 2 2], shape=(3,), dtype=int32)
tf.Tensor([24 24 24], shape=(3,), dtype=int32)
tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)
tf.Tensor([18 18 18], shape=(3,), dtype=int32)
tf.Tensor([0.16666667 0.16666667 0.16666667], shape=(3,), dtype=float32)
tf.Tensor([2 2 2], shape=(3,), dtype=int32)
tf.Tensor([-6 -6 -6], shape=(3,), dtype=int32)


In [61]:
# các phép làm tròn trong tensor

t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
print(r1)

r2 = tf.math.rint(t)
print(r2)

r3 = tf.math.ceil(t)
print(r3)

r4 = tf.math.floor(t)
print(r4)

tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


In [65]:
# các phép toán trên vector và ma trận

t1 = tf.constant([4,3,2])
t2 = tf.constant([3,2,1])
t3 = tf.constant([[1,2,3],[4,5,6]])
t4 = tf.constant([[7,8],[9,10],[11,12]])

dot_x = tf.tensordot(t1,t2, 0)
print('ma trận x: \n',dot_x)

dot_y = tf.tensordot(t3,t4, 1)
print('ma trận y: \n',dot_y)

# tính tích có hướng
cross = tf.linalg.cross(t1,t2)
print("tích có hướng ma trận: \n", cross)

# nhân ma trận
mm = tf.matmul(t3,t4)
print("nhân 2 ma trận: \n",mm)

#tạo các ma trận đường chéo
d = tf.linalg.diag(t3)
print("tạo ma trận đường chéo chính: \n",d)

# tính tổng các phân tử trên đường chéo chính
trace = tf.linalg.trace(t3)
print("tổng phần tử đường chéo chính: \n",trace)

# chuyển vị ma trận
trans = tf.transpose(t3)
print("chuyển vị ma trận: \n",trans)

# tạo ma trận có kích thước 5x5
eye = tf.eye(5,5)
print("tạo ma trận 5x5: \n",eye)

ma trận x: 
 tf.Tensor(
[[12  8  4]
 [ 9  6  3]
 [ 6  4  2]], shape=(3, 3), dtype=int32)
ma trận y: 
 tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
tích có hướng ma trận: 
 tf.Tensor([-1  2 -1], shape=(3,), dtype=int32)
nhân 2 ma trận: 
 tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
tạo ma trận đường chéo chính: 
 tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tổng phần tử đường chéo chính: 
 tf.Tensor(6, shape=(), dtype=int32)
chuyển vị ma trận: 
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tạo ma trận 5x5: 
 tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
