<a href="https://colab.research.google.com/github/hst8486-collab/thuc-hanh--deep-learning/blob/main/Ch%C3%A0o_m%E1%BB%ABng_b%E1%BA%A1n_%C4%91%E1%BA%BFn_v%E1%BB%9Bi_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# tạo mảng 1 chiều numpy

import numpy as np

my_list = [1,9,15,39]
print('list: ', my_list)
my_numpy_arr = np.array(my_list) # chuyển list sang numpy array
print('numpy array: ', my_numpy_arr)

list:  [1, 9, 15, 39]
numpy array:  [ 1  9 15 39]


In [2]:
# tạo mảng 2 chiều numpy

import numpy as np

a = np.array([(1,2,3),(4,5,6)])
print(a)
print(a.shape) # kích thước mảng
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [4]:
# tạo mảng 3 chiều

import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [7]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1

import numpy as np

a = np.zeros((2,3))
print('mảng toàn số 0: \n', a)
b = np.ones((3,3))
print('mảng toàn số 1: \n',b)

mảng toàn số 0: 
 [[0. 0. 0.]
 [0. 0. 0.]]
mảng toàn số 1: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# thay đổi kích thước mảng

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("mảng a: \n", a)
print(a.shape)

# đổi kích thước mảng
b = a.reshape(3,2)
print("mảng b: \n", b)
print(b.shape)

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("mảng c: \n", c)
print(c.shape)

d = c.reshape(3,4)
print("mảng d: \n", d)
print(d.shape)

e = d.reshape(3,2,2)
print("mảng e: \n", e)
print(e.shape)

mảng a: 
 [[1 2 3]
 [4 5 6]]
(2, 3)
mảng b: 
 [[1 2]
 [3 4]
 [5 6]]
(3, 2)
mảng c: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
mảng d: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
mảng e: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [13]:
# chuyển mảng nhiều chiều về 1 chiều

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("mảng a: \n",a)
b = a.flatten()
print("mảng b: \n", b)

mảng a: 
 [[1 2 3]
 [4 5 6]]
mảng b: 
 [1 2 3 4 5 6]


In [16]:
# thêm dòng dữ liệu

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# thêm dữ liệu theo chiều dọc
h_stack = np.hstack((a,b))
print("horizontal append: \n", h_stack)

# thêm dữ liệu theo chiều ngang
v_stack = np.vstack((a,b))
print("vertical append: \n", v_stack)

horizontal append: 
 [1 2 3 4 5 6]
vertical append: 
 [[1 2 3]
 [4 5 6]]


In [23]:
# tạo mảng ngẫu nhiên

import numpy as np

a = np.random.randint(100, size=(5,))
print("\n",a)

b = np.random.randint(100, size=(2,3))
print("\n",b)

c = np.random.randint(100, size=(3,2,3))
print("\n",c)


 [68 72 81 37 52]

 [[70 73 91]
 [86 68 63]]

 [[[24 23 46]
  [81 25 72]]

 [[52 69 54]
  [89 72 55]]

 [[62 35 42]
  [48 27 35]]]


In [27]:
# tạo pandas từ list

import pandas as pd

a = pd.Series([1,2,3,4,5])
print(a)
print("giá trị đầu: ", a[0])
b = pd.Series ([1,2,3], index = ['a','b','c'])
print(b)
print ("giá trị đầu: ", b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1
1    2
2    3
3    4
4    5
dtype: int64
giá trị đầu:  1
a    1
b    2
c    3
dtype: int64
giá trị đầu:  1
day1    420
day2    380
day3    390
dtype: int64
